### PR TITLE
Update licenseUrl and dependencies in nuspec

### PR DESCRIPTION
**Pull request by jnyrup**
Thanks for a great package!

Adding `<dependencies>` to the `nuspec` will populate the "Dependencies" section on NuGet.

### CODE REVIEW

**Comment by mbuchetics** [comment]
Trank you!

**Comment by apacha** [comment]
Just updated it to NETStandard 1.6 with the changes you suggested and published to nuget. If 1.6 is a problem, please let me know.

**Comment by jnyrup** [comment]
It's no problem for me, we are beginning to target .net standard 2.0 anyway.

But from a library perspective I would say you should strive to target to lowest possible .net standard.

**Comment by apacha** [comment]
You're probably right. So I've just reverted back to 1.2 for best compatibility.

**Pull request merged**
